<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <!-- NuGet identity -->
    <PackageId>VijayaKumbaji.Extensions.Productivity</PackageId>
    <Version>1.0.0</Version>

    <!-- Authoring metadata -->
    <Authors>Vijaya Laxmi Kumbaji</Authors>
    <Company>VijayaKumbaji</Company>
    <Description>
      Developer productivity extensions for .NET: configuration validation (ConfigGuard) and guard clause helpers.
    </Description>
    <PackageTags>dotnet;extensions;configuration;validation;guard;startup</PackageTags>

    <!-- Links (update to your real repo URL) -->
    <RepositoryUrl>https://github.com/https://github.com/vijaya33/DeveloperProductivityHelpersSoln.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <!-- License -->
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <!-- NuGet packing -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Symbols (recommended) -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <!-- Pack the package README into the nupkg root -->
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <!--<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.11" />-->
    <PackageReference Include="Microsoft.Extensions.Options" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    </ItemGroup>


  </Project>
